blank_issues_enabled: false
contact_links:
  - name: "❗Exploits"
    url: https://discord.gg/stratummc
    about: |
      Since GitHub doesn't currently support private issues, exploit reports are managed through our Discord.
      To report an exploit, please visit the #stratum-exploit-report channel.
  - name: "🗨 Questions"
    url: https://discord.gg/stratummc
    about: If you have questions or need help with any minor issues, feel free to ask us on our Discord server!