name: Stratum-Test-Plugin
version: ${version}
main: io.papermc.testplugin.TestPlugin
description: Stratum Test Plugin
author: StratumMC
api-version: ${apiversion}
load: STARTUP
bootstrapper: io.papermc.testplugin.TestPluginBootstrap
loader: io.papermc.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
dependencies:
