name: Publish PR

on:
  workflow_run:
    workflows: [ "Build Stratum" ]
    types:
      - completed

permissions:
  packages: write
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate an Application repository access token
        id: gen_repo_token
        uses: kattecon/gh-app-access-token-gen@v1
        with:
          app_id: 1408328
          private_key: ${{ secrets.PR_PUBLISHING_GH_APP_KEY }}
          repository: ${{ github.repository }}
      - name: Publish PR
        uses: PaperMC/action-pr-publishing@paper
        env:
          GITHUB_TOKEN: ${{ steps.gen_repo_token.outputs.token }}
        with:
          publishing-token: ${{ github.token }}
          uploader-workflow-name: Build Stratum
          artifacts-base-path: mc/stratum
          base-maven-url: 'https://maven-prs.papermc.io'
          self-name: 'stratum-pr-publishing[bot]'
